import path from "node:path";
import { readFileSync, mkdirSync, cpSync } from "node:fs";
import { bundle } from "@remotion/bundler";
import { renderMedia, selectComposition, openBrowser } from "@remotion/renderer";
const [scale, cacheMb] = [Number(process.argv[2]), Number(process.argv[3])];
const req = JSON.parse(readFileSync("/tmp/claude-1000/-workspaces-SNSapp/d625c436-0bd4-4cc7-a380-d79a85cae3fd/scratchpad/render-req.json", "utf8"));
const props = req.props;
const abs = (s: string) => "http://localhost:8765/" + s;
props.clips = props.clips.map((c: any) => ({ ...c, src: abs(c.src) }));
props.sfx = props.sfx.map((c: any) => ({ ...c, src: abs(c.src) }));
const pub = "/tmp/claude-1000/-workspaces-SNSapp/d625c436-0bd4-4cc7-a380-d79a85cae3fd/scratchpad/rpub3"; mkdirSync(pub, { recursive: true }); cpSync("public/fonts", pub + "/fonts", { recursive: true });
const serveUrl = process.env.SERVE_URL ?? await bundle({ entryPoint: path.join(process.cwd(), "remotion", "index.ts"), publicDir: pub });
const browser = await openBrowser("chrome");
const opts = { offthreadVideoCacheSizeInBytes: cacheMb * 1024 * 1024, offthreadVideoThreads: 1 };
const composition = await selectComposition({ serveUrl, id: "Standard", inputProps: props, puppeteerInstance: browser, ...opts });
console.log("START");
const t = Date.now();
await renderMedia({ composition, serveUrl, codec: "h264", outputLocation: "/tmp/claude-1000/-workspaces-SNSapp/d625c436-0bd4-4cc7-a380-d79a85cae3fd/scratchpad/mem-" + scale + ".mp4", inputProps: props, puppeteerInstance: browser, concurrency: 1, scale, frameRange: [0, 299], ...opts });
console.log("done", ((Date.now() - t) / 1000).toFixed(0), "s");
await browser.close({ silent: true });
